const styles = {
  preview: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    padding: "16px",
    backgroundColor: "#f6f6f6",
  },
  row: { display: "flex", gap: "6px" },
  item: {
    width: "48px",
    height: "48px",
    display: "flex",
    boxShadow: "inset 0 0 0 2px #ccc",
    borderRadius: "10%",
    backgroundColor: "#eee",
    overflow: "hidden",
  },
  url: {
    flexGrow: 1,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: "#666",
    fontSize: "20px",
  },
  cardGroup: { display: "flex", flexDirection: "column" },
  card: {
    width: "68px",
    height: "68px",
    display: "flex",
    justifyContent: "center",
    boxShadow: "inset 0 0 0 2px #ccc",
    borderRadius: "8%",
    backgroundColor: "#eee",
    overflow: "hidden",
  },
  customizations: {
    position: "absolute",
    top: "60%",
    display: "flex",
    gap: "2px",
  },
  customization: {
    width: "20px",
    height: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    color: "white",
    fontSize: "14px",
  },
  effect: {
    backgroundColor: "#ca5cfe",
    border: "1px solid #ebc1ff",
    boxShadow: "0 0 6px #ca5cfe",
  },
  cost: {
    backgroundColor: "#02e28f",
    border: "1px solid #4dfdbc",
    boxShadow: "0 0 6px #02e28f",
  },
  buff: {
    backgroundColor: "#09bfff",
    border: "1px solid #6fdaff",
    boxShadow: "0 0 6px #09bfff",
  },
  score: {
    backgroundColor: "#ff3482",
    border: "1px solid #ff9ac1",
    boxShadow: "0 0 6px #ff3482",
  },
  genki: {
    backgroundColor: "#00b1e2",
    border: "1px solid #49d8ff",
    boxShadow: "0 0 6px #00b1e2",
  },
  cardCost: { display: "flex", height: "8px", color: "#444" },
};

export default styles;
